<a href="https://colab.research.google.com/github/robertoarturomc/Visualizacion/blob/main/Ejercicio_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import datetime
import re

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

import wordcloud

# Ejercicio 5
Para este ejercicio, generarás una Nube de Palabras, pero ahora con tuits de Bill Gates.

In [4]:
tweets  = pd.read_csv("https://raw.githubusercontent.com/JoaquinAmatRodrigo/Estadistica-con-R/master/datos/datos_tweets_@BillGates.csv")
tweets.head()

,screen_name,user_id,created_at,status_id,text,retweet_count,favorite_count,is_quote_status,quote_status_id,is_retweet,...,hashtags,coordinates,place_id,place_type,place_name,place_full_name,country_code,country,bounding_box_coordinates,bounding_box_type
0,BillGates,50393960,2017-11-09T20:09:06Z,9.287161e+17,Tanzania hopes to eliminate one of the world’s...,608,2483,False,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BillGates,50393960,2017-11-08T16:39:30Z,9.283010e+17,"By investing in R&amp;D, I know we can discove...",1090,5321,False,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BillGates,50393960,2017-11-07T17:43:05Z,9.279546e+17,This unusual tool for fighting disease turns o...,830,4653,False,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BillGates,50393960,2017-11-02T17:42:19Z,9.261424e+17,My first trip to Africa with Melinda was the c...,1421,10944,False,NaN,False,...,MyGivingStory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BillGates,50393960,2017-10-30T04:01:05Z,9.248486e+17,"“The death that didn’t happen is not visible.""...",918,3508,False,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se evaluará que:

1. Generes la limpieza del texto (puedes copiar los pasos que hicimos en la clase). (1 punto)
2. Utilices algún método extra para eliminar Stopwords. (1 punto)
Ideas (puedes usar una o varias):

    a) Eliminar manualmente palabras que no te digan mucho. Por ejemplo, "http".
    b) Usar STOPWORDS de la librería wordcloud.
    c) Usar stopwords de la librería nltk.

3. Generes tu gráfico de Nube de Palabras. (2 puntos)
4. Modifiques algun(os) parámetros para modificar tu Nube de Palabras (1 punto).